### ISSUE TITLE
[BUG] Build broken on MinGW since 15c486ecdd45fcf49823fadcb7b24582cc60ddeb

### ISSUE THREAD

**Issue by jcelerier** [JoepVanlier/ysfx#135]
**Check latest release**
Fails on head

**Describe the bug**

When building on Windows with MinGW against UCRT (e.g. the same C runtime than Visual Studio): 
```
ysfx/thirdparty/WDL/source/WDL/eel2/../win32_utf8.h:291:52: error: 'wdl_utf8_chk_stat_types_assert_failed' declared as an array with a negative size
  291 | typedef char wdl_utf8_chk_stat_types_assert_failed[sizeof(struct stat) == sizeof(struct _stat) ? 1 : -1];
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**
- Any cmake build in MSYS2 Clang64 environment

**Expected behavior**
Build succeeds

**Desktop (please complete the following information):**
Windows 11

**Comment by jcelerier** [comment]
It seems to build if I put all the -D_FILE_OFFSET_BITS=64 behind `if(NOT WIN32)` (as is already the case in 2/3 in cmake.wdl.txt)
